### PR TITLE
GOAT algorithm

### PR DESCRIPTION
**Pull request by aurorarossi**
Cleaner version of #7

### CODE REVIEW

**Comment by gdalle** [comment]
Don't forget to update the docs page about algorithms, otherwise Documenter will complain that some docstrings are not shown :)
Feel free to ping me once it's ready!

**Comment by gdalle** [comment]
I did a new version where FAQ and GOAT share the same underlying code to reduce duplcation, what do you think?
During the tests I get a warning
```julia
┌ Warning: Sinkhorn algorithm (500/500): not converged
└ @ OptimalTransport ~/.julia/packages/OptimalTransport/ztQxB/src/entropic/sinkhorn_solve.jl:103
```
which is why I'm worried I might have broken something. Can you take a look?

**Comment by aurorarossi** [comment]
Sorry for the late reply, I ran the test several times and they passed. I also looked at the code and did not find any bugs.

**Comment by gdalle** [comment]
Okay then!

**Pull request merged**
